"use client";

import Link from "next/link";
import { AlertTriangle, ArrowLeft, ArrowRight, Building2, CheckCircle2, Loader2, MapPin, Package, UsersRound } from "lucide-react";
import { BrandMark } from "@/components/brand/brand-mark";
import { Button } from "@/components/ui/button";
import { useDashboardQuery } from "@/hooks/use-dashboard";
import type { DashboardSnapshot } from "@/types";

export function BranchesDashboardScreen({ organizationId }: { organizationId?: string }) {
  const query = new URLSearchParams({ period: "last_7_days", branchId: "all" });
  if (organizationId) query.set("organizationId", organizationId);
  const result = useDashboardQuery<DashboardSnapshot>(query.toString());
  if (result.loading && !result.data) return <State loading title="Preparando sucursales" detail="Validamos tu alcance antes de comparar unidades." />;
  if (result.error || !result.data) return <State title="No pudimos abrir las sucursales" detail={result.error ?? "No hay información autorizada."} />;
  const snapshot = result.data;
  if (!snapshot.capabilities.crossBranch) return <State title="Vista no disponible" detail="Tu rol o alcance no permite comparar varias sucursales." returnHref={`/app?organizationId=${encodeURIComponent(snapshot.organization.id)}`} />;
  return <main className="min-h-screen bg-[#edf4f7] p-4 text-[#102b48] sm:p-7"><div className="mx-auto max-w-6xl space-y-6"><header className="flex flex-col justify-between gap-4 rounded-[1.6rem] border border-[#d5e4eb] bg-white p-5 sm:flex-row sm:items-center"><div className="flex items-center gap-4"><BrandMark compact /><div><p className="text-xs font-extrabold uppercase tracking-[.14em] text-[#168b95]">{snapshot.organization.name}</p><h1 className="mt-1 text-2xl font-black tracking-[-.04em]">Pulso de sucursales</h1></div></div><Button asChild variant="outline" className="rounded-xl"><Link href={`/app?organizationId=${encodeURIComponent(snapshot.organization.id)}&branchId=all`}><ArrowLeft className="size-4" />Volver al tablero</Link></Button></header><section className="rounded-[1.8rem] bg-[#0b2e4b] p-6 text-white sm:p-8"><div className="flex items-start gap-4"><div className="flex size-12 shrink-0 items-center justify-center rounded-2xl bg-[#1dc4be] text-[#073047]"><Building2 className="size-6" /></div><div><h2 className="text-2xl font-black">Comparación dentro de tu alcance</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#b9ccd8]">Cada tarjeta usa configuración y movimientos persistentes. La ausencia de eventos operativos no se transforma en resultados positivos ficticios.</p></div></div></section><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{snapshot.branchSummaries.map((branch) => <Link key={branch.id} href={`/app/sucursales/${branch.id}?organizationId=${encodeURIComponent(snapshot.organization.id)}`} className="group rounded-[1.45rem] border border-[#d5e4eb] bg-white p-5 transition hover:-translate-y-0.5 hover:border-[#8ac9cc] hover:shadow-md"><div className="flex items-start justify-between gap-3"><div><p className="flex items-center gap-2 font-black text-[#183a57]"><MapPin className="size-4 text-[#168b95]" />{branch.name}</p><p className="mt-1 text-xs text-[#718699]">{branch.code} · {branch.timezone}</p></div>{branch.pendingSetup ? <span className="rounded-full bg-[#fff2d9] px-2.5 py-1 text-[10px] font-extrabold text-[#8b5d12]">{branch.pendingSetup} pendientes</span> : <CheckCircle2 className="size-5 text-[#1b9c78]" />}</div><div className="mt-5 grid grid-cols-3 gap-2 text-center"><Metric icon={UsersRound} label="Personal" value={branch.employees} /><Metric icon={Package} label="Movimientos" value={branch.inventoryMovements} /><Metric icon={CheckCircle2} label="Fuentes" value={branch.configuredSources} /></div><span className="mt-5 inline-flex items-center gap-1 text-xs font-extrabold text-[#1769df]">Abrir sucursal <ArrowRight className="size-3.5 transition group-hover:translate-x-0.5" /></span></Link>)}</div></div></main>;
}

export function BranchDashboardScreen({ organizationId, branchId }: { organizationId?: string; branchId: string }) {
  const query = new URLSearchParams({ branchId, period: "last_7_days" });
  if (organizationId) query.set("organizationId", organizationId);
  const result = useDashboardQuery<DashboardSnapshot>(query.toString());
  if (result.loading && !result.data) return <State loading title="Abriendo sucursal" detail="Validamos que esta unidad pertenezca a tu alcance." />;
  if (result.error || !result.data) return <State title="Sucursal no disponible" detail={result.error ?? "No existe una sucursal autorizada."} />;
  const snapshot = result.data;
  const branch = snapshot.branches.find((item) => item.id === snapshot.selectedBranchId);
  const summary = snapshot.branchSummaries.find((item) => item.id === snapshot.selectedBranchId);
  return <main className="min-h-screen bg-[#edf4f7] p-4 text-[#102b48] sm:p-7"><div className="mx-auto max-w-6xl space-y-6"><header className="flex flex-col justify-between gap-4 rounded-[1.6rem] border border-[#d5e4eb] bg-white p-5 sm:flex-row sm:items-center"><div><p className="text-xs font-extrabold uppercase tracking-[.14em] text-[#168b95]">{snapshot.organization.name}</p><h1 className="mt-1 text-3xl font-black tracking-[-.045em]">{branch?.name ?? "Sucursal"}</h1><p className="mt-1 text-sm text-[#6b8093]">{branch?.code} · {branch?.timezone}</p></div><Button asChild variant="outline" className="rounded-xl"><Link href={snapshot.capabilities.crossBranch ? `/app/sucursales?organizationId=${encodeURIComponent(snapshot.organization.id)}` : `/app?organizationId=${encodeURIComponent(snapshot.organization.id)}`}><ArrowLeft className="size-4" />Regresar</Link></Button></header>{summary && <div className="grid gap-3 sm:grid-cols-3"><Summary label="Personal activo" value={summary.employees} detail="Registros D1" /><Summary label="Fuentes configuradas" value={summary.configuredSources} detail="Catálogos activos" /><Summary label="Movimientos" value={summary.inventoryMovements} detail="Histórico persistente" /></div>}<section><h2 className="text-xl font-black">Indicadores autorizados</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{snapshot.widgets.filter((widget) => widget.code !== "branch_overview").map((widget) => <article key={widget.code} className={`rounded-[1.35rem] border bg-white p-5 ${widget.valueStatus === "unavailable" ? "border-dashed border-[#c7d5dc]" : "border-[#d5e4eb]"}`}><div className="flex items-start justify-between gap-3"><h3 className="font-black text-[#29465f]">{widget.name}</h3><strong className={widget.valueStatus === "unavailable" ? "text-sm text-[#718699]" : "text-2xl text-[#143653]"}>{widget.valueLabel}</strong></div><p className="mt-3 text-xs leading-5 text-[#718699]">{widget.detail}</p></article>)}</div></section>{snapshot.attention.length > 0 && <section><h2 className="text-xl font-black">Pendientes explicados</h2><div className="mt-4 space-y-3">{snapshot.attention.map((item) => <Link href={item.href} key={item.id} className="flex items-start gap-3 rounded-2xl border border-[#d5e4eb] bg-white p-4"><AlertTriangle className="mt-0.5 size-5 shrink-0 text-[#c57924]" /><span className="min-w-0 flex-1"><strong className="text-sm text-[#29465f]">{item.title}</strong><span className="mt-1 block text-xs leading-5 text-[#718699]">{item.reason}</span></span><ArrowRight className="size-4 text-[#718699]" /></Link>)}</div></section>}</div></main>;
}

function Metric({ icon: Icon, label, value }: { icon: typeof UsersRound; label: string; value: number }) { return <div className="rounded-xl bg-[#f2f7fa] p-3"><Icon className="mx-auto size-4 text-[#168b95]" /><strong className="mt-1 block text-lg text-[#183a57]">{value}</strong><span className="text-[10px] text-[#718699]">{label}</span></div>; }
function Summary({ label, value, detail }: { label: string; value: number; detail: string }) { return <article className="rounded-[1.35rem] border border-[#d5e4eb] bg-white p-5"><strong className="text-3xl font-black text-[#143653]">{value}</strong><p className="mt-3 text-sm font-black text-[#29465f]">{label}</p><p className="mt-1 text-xs text-[#718699]">{detail}</p></article>; }
function State({ loading = false, title, detail, returnHref = "/app" }: { loading?: boolean; title: string; detail: string; returnHref?: string }) { return <main className="flex min-h-screen items-center justify-center bg-[#edf4f7] p-5"><div className="w-full max-w-md rounded-[1.7rem] border border-[#d5e4eb] bg-white p-8 text-center"><BrandMark /><div className="mx-auto mt-6 flex size-11 items-center justify-center rounded-xl bg-[#e8f3ff] text-[#1769df]">{loading ? <Loader2 className="size-5 animate-spin" /> : <AlertTriangle className="size-5" />}</div><h1 className="mt-4 text-2xl font-black">{title}</h1><p className="mt-2 text-sm leading-6 text-[#6b8093]">{detail}</p>{!loading && <Button asChild variant="outline" className="mt-6 rounded-xl"><Link href={returnHref}>Regresar</Link></Button>}</div></main>; }
