"use client";

import Link from "next/link";
import { ArrowRight, CalendarClock, CircleDollarSign, FilePlus2, NotebookTabs, Plus, UsersRound } from "lucide-react";
import { CommercialError, CommercialLoading, StatusBadge, formatPlatformDate } from "@/components/platform/commercial-shared";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useCommercialQuery } from "@/hooks/use-commercial";
import type { CommercialOverview } from "@/types";
import { formatMinorMoney } from "@/utils/money";

export function CommercialOverviewPanel() {
  const { data, error, loading, refresh } = useCommercialQuery<CommercialOverview>("view=overview");
  if (loading && !data) return <CommercialLoading label="Calculando indicadores comerciales reales…" />;
  if (error || !data) return <CommercialError message={error ?? "Indicadores no disponibles."} onRetry={() => void refresh()} />;
  return <section className="space-y-4">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-black text-[#183451]">Operación comercial</h2><p className="mt-1 text-sm text-[#6a7e94]">Indicadores calculados desde prospectos, seguimientos y cotizaciones persistentes.</p></div><div className="flex flex-wrap gap-2"><Button asChild variant="outline" className="rounded-xl"><Link href="/platform/cotizaciones"><NotebookTabs className="size-4" />Cotizaciones</Link></Button><Button asChild className="rounded-xl"><Link href="/platform/prospectos/nuevo"><Plus className="size-4" />Nueva oportunidad</Link></Button></div></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={UsersRound} label="Prospectos nuevos" value={String(data.newProspects)} detail={`${data.activeOpportunities} oportunidades activas`} /><Metric icon={CalendarClock} label="Seguimientos vencidos" value={String(data.overdueFollowUps)} detail={`${data.upcomingFollowUps} próximos en 7 días`} /><Metric icon={FilePlus2} label="Diagnósticos en proceso" value={String(data.diagnosesInProgress)} detail={`${data.draftQuotes} cotizaciones en borrador`} /><Metric icon={FilePlus2} label="Pendientes de respuesta" value={String(data.pendingQuotes)} detail={`${data.acceptedQuotes} aceptadas · ${data.expiredQuotes} vencidas`} /><Metric icon={CircleDollarSign} label="Valor mensual cotizado" value={formatMinorMoney(data.quotedMonthlyMinor, data.currency)} detail="Propuestas listas o enviadas" /><Metric icon={CircleDollarSign} label="Mensualidad aceptada estimada" value={formatMinorMoney(data.acceptedMonthlyMinor, data.currency)} detail="No equivale a ingreso cobrado" /><Metric icon={CircleDollarSign} label="Implementación cotizada" value={formatMinorMoney(data.quotedImplementationMinor, data.currency)} detail="Importe único propuesto" /><Metric icon={CircleDollarSign} label="Implementación aceptada" value={formatMinorMoney(data.acceptedImplementationMinor, data.currency)} detail="Aún no equivale a cobro" /></div>
    <div className="grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><Card className="rounded-[1.4rem] border-[#dbe7f2]"><CardHeader className="flex-row items-center justify-between"><CardTitle className="text-lg">Oportunidades recientes</CardTitle><Button asChild variant="ghost" size="sm"><Link href="/platform/prospectos">Ver todas <ArrowRight className="size-4" /></Link></Button></CardHeader><CardContent>{data.recentProspects.length ? <div className="divide-y divide-[#e5edf4]">{data.recentProspects.map((prospect) => <Link key={prospect.id} href={`/platform/prospectos/${prospect.id}`} className="flex items-center justify-between gap-4 py-3"><div><div className="flex flex-wrap items-center gap-2"><p className="font-bold text-[#314b65]">{prospect.commercialName}</p><StatusBadge status={prospect.status} /></div><p className="mt-1 text-xs text-[#71869a]">{prospect.nextAction} · {formatPlatformDate(prospect.nextActionAt)}</p></div><ArrowRight className="size-4 text-[#8aa0b4]" /></Link>)}</div> : <p className="py-7 text-center text-sm text-[#71869a]">Registra la primera oportunidad para iniciar el proceso comercial.</p>}</CardContent></Card><Card className="rounded-[1.4rem] border-[#dbe7f2]"><CardHeader><CardTitle className="text-lg">Requiere atención</CardTitle></CardHeader><CardContent>{data.attention.length ? <div className="space-y-2">{data.attention.map((item) => <Link key={item.id} href={item.href} className="block rounded-xl border border-[#f0d9a9] bg-[#fffaf0] p-3"><p className="text-sm font-bold text-[#5c4a25]">{item.title}</p><p className="mt-1 text-xs leading-5 text-[#816d44]">{item.detail}</p></Link>)}</div> : <p className="py-7 text-center text-sm text-[#71869a]">No hay seguimientos vencidos.</p>}</CardContent></Card></div>
  </section>;
}

function Metric({ icon: Icon, label, value, detail }: { icon: typeof UsersRound; label: string; value: string; detail: string }) { return <Card className="rounded-[1.3rem] border-[#dbe7f2]"><CardContent className="p-5"><div className="flex size-10 items-center justify-center rounded-xl bg-[#e8f3ff] text-[#1769e0]"><Icon className="size-5" /></div><p className="mt-4 text-2xl font-black tracking-[-0.04em] text-[#183451]">{value}</p><p className="mt-1 text-sm font-bold text-[#314b65]">{label}</p><p className="mt-1 text-xs text-[#7b8da0]">{detail}</p></CardContent></Card>; }
