"use client";

import Link from "next/link";
import { ArrowLeft, Boxes, Building2, ChefHat, ClipboardCheck, Eye, Loader2, MapPin, Package, RefreshCw, Settings2, UsersRound } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useTenancyQuery } from "@/hooks/use-tenancy";
import type { CustomerWorkspaceSnapshot } from "@/types";

export function PlatformOperationPreview({ organizationId, branchId }: { organizationId: string; branchId?: string }) {
  const query = useTenancyQuery<CustomerWorkspaceSnapshot>(`view=workspace&id=${encodeURIComponent(organizationId)}${branchId ? `&branchId=${encodeURIComponent(branchId)}` : ""}`);
  if (query.loading && !query.data) return <div className="flex min-h-80 items-center justify-center gap-2 text-sm text-[#6b8093]"><Loader2 className="size-5 animate-spin" />Preparando vista operativa…</div>;
  if (query.error || !query.data) return <Card className="rounded-2xl"><CardContent className="p-8 text-center"><p className="font-black text-[#183a57]">No fue posible abrir la operación</p><p className="mt-2 text-sm text-[#6b8093]">{query.error ?? "La organización no existe."}</p></CardContent></Card>;
  const snapshot = query.data;
  const branch = snapshot.branches.find((item) => item.id === snapshot.currentBranchId) ?? snapshot.branches[0];
  const metrics = [
    { label: "Personal", value: snapshot.metrics.employees, detail: `${snapshot.metrics.shifts} turnos`, icon: UsersRound },
    { label: "Servicios", value: snapshot.metrics.serviceTypes, detail: "tipos configurados", icon: ChefHat },
    { label: "Calidad", value: snapshot.metrics.qualityTemplates, detail: "plantillas activas", icon: ClipboardCheck },
    { label: "Inventario", value: snapshot.metrics.products, detail: `${snapshot.metrics.inventoryMovements} movimientos`, icon: Boxes },
  ];
  return <div className="space-y-6">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><Button asChild variant="ghost" size="sm" className="min-h-10"><Link href={`/platform/organizaciones/${organizationId}`}><ArrowLeft className="size-4" />Volver a la organización</Link></Button><div className="flex items-center gap-2"><Badge className="bg-[#fff2d9] text-[#8d5d12]"><Eye className="mr-1 size-3.5" />Supervisión de Platform</Badge>{snapshot.branches.length > 1 && <select className="h-11 rounded-xl border border-[#cbdbe4] bg-white px-3 text-sm font-bold" value={snapshot.currentBranchId} onChange={(event) => window.location.assign(`/platform/organizaciones/${organizationId}/operacion?branchId=${encodeURIComponent(event.target.value)}`)} aria-label="Cambiar sucursal supervisada">{snapshot.branches.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>}<Button variant="outline" size="icon" className="size-11 rounded-xl" aria-label="Actualizar" onClick={() => void query.refresh()}><RefreshCw className="size-4" /></Button></div></div>
    <section className="relative overflow-hidden rounded-[2rem] bg-[#0b2d4a] p-6 text-white sm:p-8"><div className="pointer-events-none absolute -right-16 -top-24 size-72 rounded-full bg-[#1dc4be]/20 blur-3xl" /><div className="relative"><div className="flex flex-wrap gap-2 text-xs font-bold text-[#a9c0cd]"><span className="rounded-full bg-white/10 px-3 py-1">{snapshot.organization.code}</span><span className="flex items-center gap-1 rounded-full bg-white/10 px-3 py-1"><MapPin className="size-3.5" />{branch?.name}</span></div><h1 className="mt-5 text-3xl font-black tracking-[-0.05em] sm:text-4xl">{snapshot.organization.commercialName}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#b9ccd8]">Vista de supervisión con los mismos datos persistentes que verá el cliente. Esta entrada no crea una membresía ni suplanta su identidad.</p></div></section>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({ label, value, detail, icon: Icon }) => <Card key={label} className="rounded-[1.35rem] border-[#d5e4eb]"><CardContent className="p-5"><div className="flex items-start justify-between"><div className="flex size-10 items-center justify-center rounded-xl bg-[#e8f4f5] text-[#148a93]"><Icon className="size-5" /></div><strong className="text-3xl font-black text-[#143653]">{value}</strong></div><p className="mt-5 text-sm font-black text-[#29465f]">{label}</p><p className="mt-1 text-xs text-[#718699]">{detail}</p></CardContent></Card>)}</div>
    <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><Card className="rounded-[1.5rem] border-[#d5e4eb]"><CardContent className="p-5 sm:p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-[#168b95]">Módulos contratados</p><h2 className="mt-1 text-xl font-black text-[#183a57]">Alcance visible</h2></div><Building2 className="size-6 text-[#1769df]" /></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{snapshot.moduleCodes.map((code) => <div key={code} className="rounded-xl bg-[#f2f7fa] p-3"><p className="text-sm font-black text-[#29465f]">{code}</p><p className="mt-1 text-xs text-[#718699]">Entitlement activo y verificado.</p></div>)}</div></CardContent></Card><Card className="rounded-[1.5rem] border-[#d5e4eb]"><CardContent className="p-5 sm:p-6"><Settings2 className="size-6 text-[#168b95]" /><h2 className="mt-4 text-xl font-black text-[#183a57]">Preparación</h2><p className="mt-2 text-sm leading-6 text-[#6b8093]">Onboarding: <strong>{snapshot.onboarding.progress}%</strong> · {snapshot.onboarding.status.replaceAll("_", " ")}.</p><p className="mt-3 text-xs leading-5 text-[#718699]">Los módulos operativos que aún dependen del piloto no se presentan como productivos en esta vista.</p><Button asChild variant="outline" className="mt-5 w-full rounded-xl"><Link href={`/platform/organizaciones/${organizationId}`}><Package className="size-4" />Revisar implementación</Link></Button></CardContent></Card></div>
  </div>;
}
