"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, CopyPlus, LockKeyhole, Save } from "lucide-react";
import { toast } from "sonner";
import { CommercialError, CommercialLoading, formatPlatformDate } from "@/components/platform/commercial-shared";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { commercialMutation, useCommercialQuery } from "@/hooks/use-commercial";
import type { PriceBookDetail } from "@/types";
import { formatMinorMoney } from "@/utils/money";

export function PriceBookDetailScreen({ priceBookId }: { priceBookId: string }) {
  const [versionId, setVersionId] = useState("");
  const query = `view=price_book&id=${encodeURIComponent(priceBookId)}${versionId ? `&versionId=${encodeURIComponent(versionId)}` : ""}`;
  const { data, error, loading, refresh } = useCommercialQuery<PriceBookDetail>(query);
  if (loading && !data) return <CommercialLoading label="Abriendo catálogo versionado…" />;
  if (error || !data) return <CommercialError message={error ?? "Catálogo no disponible."} onRetry={() => void refresh()} />;
  return <PriceBookWorkspace book={data} selectedVersionId={versionId} setSelectedVersionId={setVersionId} refresh={refresh} />;
}

function PriceBookWorkspace({ book, selectedVersionId, setSelectedVersionId, refresh }: { book: PriceBookDetail; selectedVersionId: string; setSelectedVersionId: (value: string) => void; refresh: () => Promise<void> }) {
  const version = book.selectedVersion;
  const [busy, setBusy] = useState(false);
  const [effectiveFrom, setEffectiveFrom] = useState(new Date().toISOString().slice(0, 10));
  const [notes, setNotes] = useState(version?.notes ?? "Revisión comercial aprobada por la fundadora.");
  const [confirmation, setConfirmation] = useState("");
  const run = async (task: () => Promise<unknown>, message: string) => { setBusy(true); try { await task(); toast.success(message); await refresh(); } catch (requestError) { toast.error(requestError instanceof Error ? requestError.message : "No fue posible guardar."); } finally { setBusy(false); } };
  return <div className="space-y-6">
    <div><Button asChild variant="ghost" className="-ml-3 rounded-xl text-[#60758b]"><Link href="/platform/precios"><ArrowLeft className="size-4" />Catálogos de precios</Link></Button><div className="mt-3 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-[#169b99]">Catálogo versionado</p><h1 className="mt-1 text-3xl font-black tracking-[-0.04em] text-[#102b48]">{book.name}</h1><p className="mt-2 text-[#6a7e94]">{book.currency} · {book.countryCode ?? "Mercado global"}</p></div><div className="flex gap-2"><Select value={selectedVersionId || version?.id || ""} onValueChange={setSelectedVersionId}><SelectTrigger className="w-48 bg-white"><SelectValue placeholder="Versión" /></SelectTrigger><SelectContent>{book.versions.map((item) => <SelectItem key={item.id} value={item.id}>v{item.versionNumber} · {item.status}</SelectItem>)}</SelectContent></Select>{!book.draftVersionId && <Button disabled={busy} onClick={() => void run(async () => { const result = await commercialMutation<{ versionId: string }>("revise_price_book", { priceBookId: book.id, notes: "Nueva revisión comercial" }); setSelectedVersionId(result.versionId); }, "Nueva revisión creada.")}><CopyPlus className="size-4" />Nueva revisión</Button>}</div></div></div>
    {!version ? <CommercialError message="Esta lista no tiene versiones." onRetry={() => void refresh()} /> : <>
      <Alert className={`rounded-2xl ${version.status === "draft" ? "border-[#efcf78] bg-[#fffaf0]" : "border-[#bfe7e2] bg-[#f4fffd]"}`}><LockKeyhole className="size-4" /><AlertTitle>{version.status === "draft" ? "Borrador editable: aún no puede usarse para cotizaciones listas" : "Versión inmutable"}</AlertTitle><AlertDescription>{version.status === "draft" ? "Revisa importes, costos internos y rangos. Publicar requiere confirmación explícita." : `Publicada ${formatPlatformDate(book.versions.find((item) => item.id === version.id)?.publishedAt ?? null)}. Las cotizaciones históricas conservan esta versión.`}</AlertDescription></Alert>
      <Card className="rounded-[1.4rem] border-[#dbe7f2]"><CardHeader><CardTitle>Reglas de precio · versión {version.versionNumber}</CardTitle></CardHeader><CardContent className="space-y-3">{version.rules.map((rule) => <PriceRuleRow key={`${rule.id}-${JSON.stringify(rule.tiers)}`} rule={rule} currency={book.currency} editable={version.status === "draft"} busy={busy} onSave={(unitAmountMinor, internalCostMinor) => run(() => commercialMutation("update_price_rule", { priceBookId: book.id, versionId: version.id, ruleId: rule.id, unitAmountMinor, internalCostMinor }), `${rule.name} actualizado.`)} onSaveTiers={(tiers) => run(() => commercialMutation("update_price_tiers", { priceBookId: book.id, versionId: version.id, ruleId: rule.id, tiers }), `Rangos de ${rule.name} actualizados.`)} />)}</CardContent></Card>
      {version.status === "draft" && <Card className="rounded-[1.4rem] border-[#c9dceb]"><CardHeader><CardTitle>Publicar versión</CardTitle></CardHeader><CardContent className="grid gap-4 lg:grid-cols-[180px_1fr_180px_auto]"><Field label="Vigencia desde"><Input type="date" value={effectiveFrom} onChange={(event) => setEffectiveFrom(event.target.value)} /></Field><Field label="Notas de publicación"><Textarea rows={2} value={notes} onChange={(event) => setNotes(event.target.value)} /></Field><Field label="Escribe PUBLICAR"><Input value={confirmation} onChange={(event) => setConfirmation(event.target.value.toUpperCase())} /></Field><Button className="mt-auto" disabled={busy || confirmation !== "PUBLICAR" || notes.trim().length < 3} onClick={() => void run(() => commercialMutation("publish_price_book", { priceBookId: book.id, versionId: version.id, effectiveFrom, notes, confirmation }), "Catálogo publicado e inmutable.")}><CheckCircle2 className="size-4" />Publicar</Button></CardContent></Card>}
    </>}
  </div>;
}

function PriceRuleRow({ rule, currency, editable, busy, onSave, onSaveTiers }: { rule: PriceBookDetail["selectedVersion"] extends infer V ? V extends { rules: Array<infer R> } ? R : never : never; currency: string; editable: boolean; busy: boolean; onSave: (unit: number, cost: number | null) => Promise<void>; onSaveTiers: (tiers: Array<{ minimumQuantity: number; maximumQuantity: number | null; unitAmountMinor: number; flatAmountMinor: number }>) => Promise<void> }) {
  const [amount, setAmount] = useState((rule.unitAmountMinor / 100).toFixed(2));
  const [cost, setCost] = useState(rule.internalCostMinor === null ? "" : (rule.internalCostMinor / 100).toFixed(2));
  const [tierDrafts, setTierDrafts] = useState(() => rule.tiers.map((tier) => ({ minimumQuantity: String(tier.minimumQuantity), maximumQuantity: tier.maximumQuantity === null ? "" : String(tier.maximumQuantity), unitAmount: (tier.unitAmountMinor / 100).toFixed(2), flatAmount: (tier.flatAmountMinor / 100).toFixed(2) })));
  const saveTiers = () => onSaveTiers(tierDrafts.map((tier) => ({ minimumQuantity: Math.max(0, Number(tier.minimumQuantity) || 0), maximumQuantity: tier.maximumQuantity.trim() ? Math.max(0, Number(tier.maximumQuantity)) : null, unitAmountMinor: Math.max(0, Math.round((Number(tier.unitAmount) || 0) * 100)), flatAmountMinor: Math.max(0, Math.round((Number(tier.flatAmount) || 0) * 100)) })));
  return <div className="rounded-2xl border border-[#e0e9f1] bg-[#f9fbfd] p-4"><div className="grid gap-3 lg:grid-cols-[minmax(260px,1fr)_140px_150px_150px_auto] lg:items-end"><div><div className="flex flex-wrap items-center gap-2"><p className="font-extrabold text-[#314b65]">{rule.name}</p><Badge variant="outline">{rule.billingPeriod}</Badge>{rule.moduleCode && <Badge className="bg-[#e8f2ff] text-[#1769e0]">{rule.moduleCode}</Badge>}</div><p className="mt-1 text-xs leading-5 text-[#71869a]">{rule.description}</p>{rule.tiers.length > 0 && <p className="mt-2 text-xs font-bold text-[#61778d]">Los rangos deben ser continuos y no pueden superponerse.</p>}</div><Field label="Tipo"><Input value={rule.chargeType} disabled /></Field><Field label={`Precio (${currency})`}><Input type="number" min="0" step="0.01" value={amount} disabled={!editable} onChange={(event) => setAmount(event.target.value)} /></Field><Field label="Costo interno"><Input type="number" min="0" step="0.01" value={cost} disabled={!editable} onChange={(event) => setCost(event.target.value)} /></Field>{editable ? <Button variant="outline" disabled={busy} onClick={() => void onSave(Math.round(Number(amount) * 100), cost ? Math.round(Number(cost) * 100) : null)}><Save className="size-4" />Guardar</Button> : <p className="pb-2 text-right text-sm font-black text-[#1769e0]">{formatMinorMoney(rule.unitAmountMinor, currency)}</p>}</div>{tierDrafts.length > 0 && <div className="mt-4 border-t border-[#dce7ef] pt-4"><div className="space-y-2">{tierDrafts.map((tier, index) => <div key={`${rule.id}-tier-${index}`} className="grid gap-2 sm:grid-cols-4"><Field label="Desde"><Input type="number" min="0" disabled={!editable} value={tier.minimumQuantity} onChange={(event) => setTierDrafts((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, minimumQuantity: event.target.value } : item))} /></Field><Field label="Hasta (vacío = ∞)"><Input type="number" min="0" disabled={!editable} value={tier.maximumQuantity} onChange={(event) => setTierDrafts((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, maximumQuantity: event.target.value } : item))} /></Field><Field label={`Unitario (${currency})`}><Input type="number" min="0" step="0.01" disabled={!editable} value={tier.unitAmount} onChange={(event) => setTierDrafts((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, unitAmount: event.target.value } : item))} /></Field><Field label={`Fijo (${currency})`}><Input type="number" min="0" step="0.01" disabled={!editable} value={tier.flatAmount} onChange={(event) => setTierDrafts((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, flatAmount: event.target.value } : item))} /></Field></div>)}</div>{editable && <div className="mt-3 flex justify-end"><Button variant="outline" disabled={busy} onClick={() => void saveTiers()}><Save className="size-4" />Guardar rangos</Button></div>}</div>}</div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
