"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, BadgeCheck, CalendarPlus, Check, ClipboardCheck, FilePlus2, Mail, NotebookPen, Phone, Plus, RefreshCw, Save, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { CommercialError, CommercialLoading, PROSPECT_STATUS_LABELS, StatusBadge, formatPlatformDate } from "@/components/platform/commercial-shared";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { DIAGNOSIS_SECTION_LABELS } from "@/constants/commercial-catalog";
import { commercialMutation, useCommercialQuery } from "@/hooks/use-commercial";
import type { DiagnosisQuestion, ProspectDetail, ProspectStatus } from "@/types";
import { formatMinorMoney } from "@/utils/money";

export function ProspectDetailScreen({ prospectId }: { prospectId: string }) {
  const { data, error, loading, refresh } = useCommercialQuery<ProspectDetail>(`view=prospect&id=${encodeURIComponent(prospectId)}`);
  if (loading && !data) return <CommercialLoading label="Abriendo expediente comercial…" />;
  if (error || !data) return <CommercialError message={error ?? "No se encontró el prospecto."} onRetry={() => void refresh()} />;
  return <ProspectWorkspace prospect={data} refresh={refresh} />;
}

function ProspectWorkspace({ prospect, refresh }: { prospect: ProspectDetail; refresh: () => Promise<void> }) {
  const [busy, setBusy] = useState(false);
  const [status, setStatus] = useState<ProspectStatus>(prospect.status);
  const [statusReason, setStatusReason] = useState("");
  const run = async (task: () => Promise<unknown>, message: string) => {
    setBusy(true);
    try { await task(); toast.success(message); await refresh(); }
    catch (requestError) { toast.error(requestError instanceof Error ? requestError.message : "No fue posible guardar el cambio."); }
    finally { setBusy(false); }
  };
  return <div className="space-y-6">
    <div><Button asChild variant="ghost" className="-ml-3 rounded-xl text-[#60758b]"><Link href="/platform/prospectos"><ArrowLeft className="size-4" />Prospectos</Link></Button><div className="mt-3 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-[#169b99]">Expediente comercial</p><StatusBadge status={prospect.status} /></div><h1 className="mt-2 text-3xl font-black tracking-[-0.04em] text-[#102b48]">{prospect.commercialName}</h1><p className="mt-2 text-[#6a7e94]">{prospect.businessType.replaceAll("_", " ")} · {prospect.city}, {prospect.countryCode} · actualizado {formatPlatformDate(prospect.updatedAt)}</p></div><div className="flex flex-wrap gap-2"><Button asChild variant="outline" className="rounded-xl"><Link href={`/platform/cotizaciones/nueva?prospectId=${prospect.id}`}><FilePlus2 className="size-4" />Nueva cotización</Link></Button><Button className="rounded-xl" onClick={() => document.getElementById("diagnosis-tab")?.click()}><ClipboardCheck className="size-4" />Continuar diagnóstico</Button></div></div></div>
    <div className="grid gap-4 md:grid-cols-4">
      <Fact label="Avance del diagnóstico" value={`${prospect.diagnosis?.completionPercentage ?? 0}%`} detail={prospect.diagnosis ? `Revisión ${prospect.diagnosis.versionNumber} · ${prospect.diagnosis.status}` : "Sin diagnóstico"} />
      <Fact label="Tamaño estimado" value={`${prospect.estimatedEmployees}`} detail={`${prospect.estimatedBranches} sucursales · ${prospect.estimatedDevices} dispositivos`} />
      <Fact label="Cotizaciones" value={String(prospect.quotes.length)} detail={prospect.quotes[0] ? `${prospect.quotes[0].quoteNumber} · ${PROSPECT_STATUS_LABELS[prospect.status]}` : "Aún no creadas"} />
      <Fact label="Siguiente acción" value={prospect.nextActionAt ? new Date(prospect.nextActionAt).toLocaleDateString("es-MX", { day: "2-digit", month: "short" }) : "Sin fecha"} detail={prospect.nextAction} />
    </div>
    <Tabs defaultValue="summary" className="space-y-4">
      <TabsList className="h-auto w-full justify-start overflow-x-auto rounded-2xl bg-white p-1.5 shadow-sm">
        <TabsTrigger value="summary">Resumen</TabsTrigger><TabsTrigger value="contacts">Contactos</TabsTrigger><TabsTrigger id="diagnosis-tab" value="diagnosis">Diagnóstico</TabsTrigger><TabsTrigger value="solution">Solución</TabsTrigger><TabsTrigger value="quotes">Cotizaciones</TabsTrigger><TabsTrigger value="followups">Seguimientos</TabsTrigger><TabsTrigger value="notes">Notas internas</TabsTrigger><TabsTrigger value="activity">Actividad</TabsTrigger>
      </TabsList>
      <TabsContent value="summary"><SummaryTab prospect={prospect} status={status} setStatus={setStatus} statusReason={statusReason} setStatusReason={setStatusReason} busy={busy} run={run} /></TabsContent>
      <TabsContent value="contacts"><ContactsTab prospect={prospect} busy={busy} run={run} /></TabsContent>
      <TabsContent value="diagnosis"><DiagnosisTab prospect={prospect} busy={busy} run={run} /></TabsContent>
      <TabsContent value="solution"><SolutionTab prospect={prospect} /></TabsContent>
      <TabsContent value="quotes"><QuotesTab prospect={prospect} /></TabsContent>
      <TabsContent value="followups"><FollowUpsTab prospect={prospect} busy={busy} run={run} /></TabsContent>
      <TabsContent value="notes"><NotesTab prospect={prospect} busy={busy} run={run} /></TabsContent>
      <TabsContent value="activity"><ActivityTab prospect={prospect} /></TabsContent>
    </Tabs>
  </div>;
}

type Runner = (task: () => Promise<unknown>, message: string) => Promise<void>;

function SummaryTab({ prospect, status, setStatus, statusReason, setStatusReason, busy, run }: { prospect: ProspectDetail; status: ProspectStatus; setStatus: (value: ProspectStatus) => void; statusReason: string; setStatusReason: (value: string) => void; busy: boolean; run: Runner }) {
  const [nextAction, setNextAction] = useState(prospect.nextAction);
  const [nextActionAt, setNextActionAt] = useState(prospect.nextActionAt ? new Date(prospect.nextActionAt).toISOString().slice(0, 16) : "");
  return <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]">
    <Card className="rounded-[1.4rem] border-[#dbe7f2]"><CardHeader><CardTitle>Situación actual</CardTitle></CardHeader><CardContent className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><TextFact label="Necesidad principal" value={prospect.primaryNeed} /><TextFact label="Problemas actuales" value={prospect.currentProblems || "No documentados"} /><TextFact label="Sistemas actuales" value={prospect.currentSystems || "No documentados"} /><TextFact label="Responsable" value={prospect.ownerName} /></div><div className="grid gap-3 rounded-2xl border border-[#dbe7f2] bg-[#f7fafd] p-4 sm:grid-cols-[1fr_220px_auto]"><Field label="Siguiente acción"><Input value={nextAction} onChange={(event) => setNextAction(event.target.value)} /></Field><Field label="Fecha"><Input type="datetime-local" value={nextActionAt} onChange={(event) => setNextActionAt(event.target.value)} /></Field><Button className="mt-auto" disabled={busy || nextAction.trim().length < 3} onClick={() => void run(() => commercialMutation("update_prospect", { id: prospect.id, version: prospect.version, changes: { nextAction, nextActionAt: nextActionAt ? new Date(nextActionAt).toISOString() : null } }), "Siguiente acción actualizada.")}><Save className="size-4" />Guardar</Button></div></CardContent></Card>
    <Card className="rounded-[1.4rem] border-[#dbe7f2]"><CardHeader><CardTitle>Estado de oportunidad</CardTitle></CardHeader><CardContent className="space-y-4"><Field label="Nuevo estado"><Select value={status} onValueChange={(value) => setStatus(value as ProspectStatus)}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{Object.entries(PROSPECT_STATUS_LABELS).map(([key, label]) => <SelectItem key={key} value={key}>{label}</SelectItem>)}</SelectContent></Select></Field>{(status === "lost" || status === "archived") && <Field label="Motivo obligatorio"><Textarea value={statusReason} onChange={(event) => setStatusReason(event.target.value)} /></Field>}<Button className="w-full rounded-xl" variant={status === "lost" || status === "archived" ? "destructive" : "default"} disabled={busy || status === prospect.status || ((status === "lost" || status === "archived") && statusReason.trim().length < 3)} onClick={() => void run(() => commercialMutation(status === "archived" ? "archive_prospect" : "transition_prospect", { id: prospect.id, version: prospect.version, status, reason: statusReason || null }), "Estado comercial actualizado.")}>Actualizar estado</Button><p className="text-xs leading-5 text-[#71869a]">Toda transición registra actor, fecha, estado anterior, estado nuevo y motivo cuando corresponde.</p></CardContent></Card>
  </div>;
}

function ContactsTab({ prospect, busy, run }: { prospect: ProspectDetail; busy: boolean; run: Runner }) {
  const [form, setForm] = useState({ name: "", position: "", email: "", phone: "", isPrimary: false });
  return <div className="grid gap-5 lg:grid-cols-[1fr_380px]"><div className="grid gap-3">{prospect.contacts.map((contact) => <Card key={contact.id} className="rounded-2xl border-[#dbe7f2]"><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><p className="font-extrabold text-[#203a57]">{contact.name}</p>{contact.isPrimary && <Badge className="bg-[#e4faf4] text-[#087c65]"><BadgeCheck className="size-3" />Principal</Badge>}</div><p className="mt-1 text-sm text-[#6a7e94]">{contact.position || "Sin puesto"}</p></div><div className="text-sm text-[#526b82]"><p className="flex items-center gap-2"><Mail className="size-4" />{contact.email}</p><p className="mt-1 flex items-center gap-2"><Phone className="size-4" />{contact.phone}</p></div></CardContent></Card>)}</div><Card className="h-fit rounded-[1.4rem] border-[#dbe7f2]"><CardHeader><CardTitle className="text-lg">Agregar contacto</CardTitle></CardHeader><CardContent className="space-y-3"><Field label="Nombre"><Input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></Field><Field label="Puesto"><Input value={form.position} onChange={(event) => setForm({ ...form, position: event.target.value })} /></Field><Field label="Correo"><Input type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></Field><Field label="Teléfono"><Input value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></Field><label className="flex items-center gap-3 text-sm font-bold text-[#415a72]"><Checkbox checked={form.isPrimary} onCheckedChange={(value) => setForm({ ...form, isPrimary: value === true })} />Convertir en contacto principal</label><Button className="w-full" disabled={busy || !form.name || !form.email || !form.phone} onClick={() => void run(() => commercialMutation("add_contact", { prospectId: prospect.id, ...form }), "Contacto agregado.")}><Plus className="size-4" />Agregar</Button></CardContent></Card></div>;
}

function DiagnosisTab({ prospect, busy, run }: { prospect: ProspectDetail; busy: boolean; run: Runner }) {
  const storedAnswers = useMemo(() => Object.fromEntries((prospect.diagnosis?.answers ?? []).map((answer) => [answer.questionCode, answer.value])), [prospect.diagnosis]);
  const [answers, setAnswers] = useState<Record<string, unknown>>(storedAnswers);
  useEffect(() => {
    const timeout = window.setTimeout(() => setAnswers(storedAnswers), 0);
    return () => window.clearTimeout(timeout);
  }, [storedAnswers]);
  const sections = [...new Set(prospect.diagnosisQuestions.map((question) => question.sectionCode))];
  const editable = prospect.diagnosis?.status === "draft" || prospect.diagnosis?.status === "in_progress";
  return <div className="space-y-4">
    <Card className="rounded-[1.4rem] border-[#dbe7f2]"><CardContent className="grid gap-4 p-5 sm:grid-cols-[1fr_220px_auto]"><div><p className="font-extrabold text-[#183451]">Diagnóstico revisión {prospect.diagnosis?.versionNumber ?? 1}</p><p className="mt-1 text-sm text-[#6a7e94]">Las preguntas vienen de una plantilla persistente y versionada, no del componente.</p></div><div><div className="flex justify-between text-xs font-bold text-[#6a7e94]"><span>Avance obligatorio</span><span>{prospect.diagnosis?.completionPercentage ?? 0}%</span></div><Progress className="mt-2" value={prospect.diagnosis?.completionPercentage ?? 0} /></div><div className="flex gap-2">{editable ? <><Button variant="outline" disabled={busy} onClick={() => void run(() => commercialMutation("save_diagnosis", { prospectId: prospect.id, answers }), "Diagnóstico guardado.")}><Save className="size-4" />Guardar</Button><Button disabled={busy || (prospect.diagnosis?.completionPercentage ?? 0) < 100} onClick={() => void run(async () => { await commercialMutation("save_diagnosis", { prospectId: prospect.id, answers }); await commercialMutation("complete_diagnosis", { prospectId: prospect.id }); }, "Diagnóstico terminado e inmutable.")}><Check className="size-4" />Terminar</Button></> : <Button disabled={busy} onClick={() => void run(() => commercialMutation("revise_diagnosis", { prospectId: prospect.id }), "Nueva revisión creada.")}><RefreshCw className="size-4" />Crear revisión</Button>}</div></CardContent></Card>
    {sections.map((section) => <Card key={section} className="rounded-[1.4rem] border-[#dbe7f2]"><CardHeader><CardTitle className="text-lg">{DIAGNOSIS_SECTION_LABELS[section] ?? section}</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{prospect.diagnosisQuestions.filter((question) => question.sectionCode === section).map((question) => <DiagnosisField key={question.id} question={question} value={answers[question.questionCode]} disabled={!editable} onChange={(value) => setAnswers((current) => ({ ...current, [question.questionCode]: value }))} />)}</CardContent></Card>)}
  </div>;
}

function DiagnosisField({ question, value, disabled, onChange }: { question: DiagnosisQuestion; value: unknown; disabled: boolean; onChange: (value: unknown) => void }) {
  if (question.fieldType === "boolean") return <label className={`flex min-h-16 items-center gap-3 rounded-xl border p-3 ${value === true ? "border-[#9edbd5] bg-[#f2fffd]" : "border-[#dbe7f2] bg-white"}`}><Checkbox checked={value === true} disabled={disabled} onCheckedChange={(checked) => onChange(checked === true)} /><span className="text-sm font-bold text-[#3b536b]">{question.label}</span></label>;
  if (question.fieldType === "select") return <Field label={`${question.label}${question.required ? " *" : ""}`}><Select value={typeof value === "string" ? value : ""} disabled={disabled} onValueChange={onChange}><SelectTrigger className="w-full"><SelectValue placeholder="Seleccionar" /></SelectTrigger><SelectContent>{question.options.map((option) => <SelectItem key={option} value={option}>{option}</SelectItem>)}</SelectContent></Select></Field>;
  return <Field label={`${question.label}${question.required ? " *" : ""}`}><Input type={question.fieldType === "number" || question.fieldType === "currency" || question.fieldType === "percentage" ? "number" : "text"} disabled={disabled} value={typeof value === "string" || typeof value === "number" ? value : ""} onChange={(event) => onChange(question.fieldType === "number" || question.fieldType === "currency" || question.fieldType === "percentage" ? Number(event.target.value) : event.target.value)} /></Field>;
}

function SolutionTab({ prospect }: { prospect: ProspectDetail }) { return <div className="grid gap-4 md:grid-cols-2"><Card className="rounded-[1.4rem] border-[#dbe7f2]"><CardHeader><CardTitle>Módulos recomendados</CardTitle></CardHeader><CardContent><div className="flex flex-wrap gap-2">{prospect.recommendedModuleCodes.map((module) => <Badge key={module} className="bg-[#e8f2ff] px-3 py-1.5 text-[#1769e0]">{module.toUpperCase()}</Badge>)}</div><p className="mt-4 text-sm leading-6 text-[#6a7e94]">La recomendación combina el perfil con las respuestas afirmativas. La decisión comercial final permanece editable en la cotización.</p></CardContent></Card><Card className="rounded-[1.4rem] border-[#dbe7f2]"><CardHeader><CardTitle>Cantidades precargadas</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-3"><TextFact label="Sucursales" value={String(prospect.estimatedBranches)} /><TextFact label="Empleados" value={String(prospect.estimatedEmployees)} /><TextFact label="Usuarios" value={String(prospect.estimatedAdminUsers)} /><TextFact label="Dispositivos" value={String(prospect.estimatedDevices)} /><TextFact label="Almacenes" value={String(prospect.estimatedWarehouses)} /><TextFact label="Movimientos / mes" value={String(prospect.estimatedMonthlyMovements ?? 0)} /></CardContent></Card></div>; }

function QuotesTab({ prospect }: { prospect: ProspectDetail }) { return <div className="space-y-3"><div className="flex justify-end"><Button asChild><Link href={`/platform/cotizaciones/nueva?prospectId=${prospect.id}`}><FilePlus2 className="size-4" />Nueva cotización</Link></Button></div>{prospect.quotes.length ? prospect.quotes.map((quote) => <Link key={quote.id} href={`/platform/cotizaciones/${quote.id}`} className="flex flex-col gap-3 rounded-2xl border border-[#dbe7f2] bg-white p-4 hover:border-[#a9caec] sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><p className="font-extrabold text-[#203a57]">{quote.quoteNumber}</p><StatusBadge status={quote.status} /></div><p className="mt-1 text-sm text-[#6a7e94]">Versión {quote.currentVersionNumber} · vigente hasta {formatPlatformDate(quote.validUntil, false)}</p></div><div className="text-right"><p className="text-lg font-black text-[#1769e0]">{formatMinorMoney(quote.monthlyTotalMinor, quote.currency)} / mes</p><p className="text-xs text-[#7b8da0]">Implementación {formatMinorMoney(quote.oneTimeTotalMinor, quote.currency)}</p></div></Link>) : <EmptyMessage text="Aún no existen cotizaciones para este prospecto." />}</div>; }

function FollowUpsTab({ prospect, busy, run }: { prospect: ProspectDetail; busy: boolean; run: Runner }) {
  const [description, setDescription] = useState(""); const [scheduledAt, setScheduledAt] = useState(""); const [type, setType] = useState("call"); const [result, setResult] = useState<Record<string, string>>({});
  const [renderedAt] = useState(() => Date.now());
  return <div className="grid gap-5 lg:grid-cols-[1fr_380px]"><div className="space-y-3">{prospect.followUps.length ? prospect.followUps.map((followUp) => <Card key={followUp.id} className="rounded-2xl border-[#dbe7f2]"><CardContent className="p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><div className="flex items-center gap-2"><p className="font-extrabold text-[#203a57]">{followUp.description}</p><Badge className={followUp.status === "completed" ? "bg-[#e4faf4] text-[#087c65]" : new Date(followUp.scheduledAt).getTime() < renderedAt ? "bg-[#fff0ed] text-[#ac3f2b]" : "bg-[#e8f2ff] text-[#1769e0]"}>{followUp.status === "completed" ? "Completado" : "Pendiente"}</Badge></div><p className="mt-1 text-sm text-[#6a7e94]">{followUp.type} · {formatPlatformDate(followUp.scheduledAt)} · {followUp.responsibleName}</p>{followUp.result && <p className="mt-2 text-sm text-[#425a72]">Resultado: {followUp.result}</p>}</div></div>{followUp.status === "pending" && <div className="mt-3 flex gap-2"><Input value={result[followUp.id] ?? ""} onChange={(event) => setResult({ ...result, [followUp.id]: event.target.value })} placeholder="Resultado del seguimiento" /><Button disabled={busy || (result[followUp.id]?.trim().length ?? 0) < 2} onClick={() => void run(() => commercialMutation("complete_follow_up", { id: followUp.id, result: result[followUp.id] }), "Seguimiento completado.")}>Completar</Button></div>}</CardContent></Card>) : <EmptyMessage text="No hay seguimientos registrados." />}</div><Card className="h-fit rounded-[1.4rem] border-[#dbe7f2]"><CardHeader><CardTitle className="text-lg">Programar seguimiento</CardTitle></CardHeader><CardContent className="space-y-3"><Field label="Tipo"><Select value={type} onValueChange={setType}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="call">Llamada</SelectItem><SelectItem value="meeting">Reunión</SelectItem><SelectItem value="email">Correo</SelectItem><SelectItem value="visit">Visita</SelectItem></SelectContent></Select></Field><Field label="Fecha y hora"><Input type="datetime-local" value={scheduledAt} onChange={(event) => setScheduledAt(event.target.value)} /></Field><Field label="Descripción"><Textarea value={description} onChange={(event) => setDescription(event.target.value)} /></Field><Button className="w-full" disabled={busy || !scheduledAt || description.trim().length < 3} onClick={() => void run(() => commercialMutation("add_follow_up", { prospectId: prospect.id, type, scheduledAt: new Date(scheduledAt).toISOString(), description }), "Seguimiento programado.")}><CalendarPlus className="size-4" />Programar</Button></CardContent></Card></div>;
}

function NotesTab({ prospect, busy, run }: { prospect: ProspectDetail; busy: boolean; run: Runner }) { const [content, setContent] = useState(""); return <div className="grid gap-5 lg:grid-cols-[1fr_380px]"><div className="space-y-3">{prospect.notes.length ? prospect.notes.map((note) => <Card key={note.id} className="rounded-2xl border-[#dbe7f2]"><CardContent className="p-4"><p className="whitespace-pre-wrap text-sm leading-6 text-[#3d556d]">{note.content}</p><p className="mt-3 text-xs font-bold text-[#8193a6]">{note.authorName} · {formatPlatformDate(note.createdAt)}</p></CardContent></Card>) : <EmptyMessage text="No hay notas comerciales internas." />}</div><Card className="h-fit rounded-[1.4rem] border-[#dbe7f2]"><CardHeader><CardTitle className="text-lg">Nota interna</CardTitle></CardHeader><CardContent><Textarea rows={6} value={content} onChange={(event) => setContent(event.target.value)} placeholder="Esta nota nunca aparecerá en la cotización ni en onboarding." /><Button className="mt-3 w-full" disabled={busy || content.trim().length < 2} onClick={() => void run(async () => { await commercialMutation("add_note", { prospectId: prospect.id, content }); setContent(""); }, "Nota guardada.")}><NotebookPen className="size-4" />Guardar nota</Button></CardContent></Card></div>; }

function ActivityTab({ prospect }: { prospect: ProspectDetail }) { return <Card className="rounded-[1.4rem] border-[#dbe7f2]"><CardHeader><CardTitle>Historial comercial</CardTitle></CardHeader><CardContent>{prospect.activity.length ? <div className="divide-y divide-[#e5edf4]">{prospect.activity.map((event) => <div key={event.id} className="flex items-start justify-between gap-4 py-3"><div><p className="text-sm font-bold text-[#314b65]">{event.action.replaceAll(".", " · ")}</p>{event.reason && <p className="mt-1 text-sm text-[#6a7e94]">{event.reason}</p>}<p className="mt-1 text-xs text-[#8193a6]">{event.actorName}</p></div><time className="shrink-0 text-xs text-[#8193a6]">{formatPlatformDate(event.createdAt)}</time></div>)}</div> : <EmptyMessage text="La actividad aparecerá al registrar acciones." />}</CardContent></Card>; }

function Fact({ label, value, detail }: { label: string; value: string; detail: string }) { return <Card className="rounded-[1.3rem] border-[#dbe7f2]"><CardContent className="p-5"><p className="text-xs font-extrabold uppercase tracking-[0.1em] text-[#7a8da3]">{label}</p><p className="mt-2 text-2xl font-black text-[#183451]">{value}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-[#71869a]">{detail}</p></CardContent></Card>; }
function TextFact({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-bold uppercase tracking-[0.09em] text-[#8395a7]">{label}</p><p className="mt-1 text-sm font-semibold leading-6 text-[#3d556d]">{value}</p></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
function EmptyMessage({ text }: { text: string }) { return <div className="rounded-2xl border border-dashed border-[#cbdce9] bg-white p-7 text-center text-sm text-[#6a7e94]"><UsersRound className="mx-auto mb-3 size-5 text-[#1769e0]" />{text}</div>; }
