import { INDUSTRIAL_MODULES } from "@/constants/modules";
import { BUSINESS_PROFILE_PRESETS, PLAN_PRESETS } from "@/constants/platform-catalog";
import type { BaseEntity, DemoState, Permission } from "@/types";

const SYSTEM_USER_ID = "user-owner-demo";
const ORGANIZATION_ID = "org-industrial-demo";
const NORTH_BRANCH_ID = "branch-north-demo";
const SOUTH_BRANCH_ID = "branch-south-demo";

function iso(minutesFromNow = 0): string {
  return new Date(Date.now() + minutesFromNow * 60_000).toISOString();
}

function base(id: string, minutesFromNow = -10_000): BaseEntity {
  const timestamp = iso(minutesFromNow);
  return { id, createdAt: timestamp, updatedAt: timestamp, createdBy: SYSTEM_USER_ID };
}

const ALL_PERMISSIONS: Permission[] = [
  "dashboard.read",
  "employees.read",
  "employees.write",
  "attendance.read",
  "attendance.adjust",
  "services.read",
  "services.override",
  "inventory.read",
  "inventory.write",
  "purchases.read",
  "purchases.write",
  "quality.read",
  "quality.write",
  "audit.read",
  "settings.manage",
];

export const demoIds = {
  organizationId: ORGANIZATION_ID,
  northBranchId: NORTH_BRANCH_ID,
  southBranchId: SOUTH_BRANCH_ID,
  ownerUserId: SYSTEM_USER_ID,
};

export function createDemoState(): DemoState {
  return {
    businessProfiles: BUSINESS_PROFILE_PRESETS.map((profile) => ({
      ...base(profile.id),
      ...profile,
      status: "active" as const,
    })),
    plans: PLAN_PRESETS.map((plan) => ({
      ...base(plan.id),
      ...plan,
      status: "active" as const,
    })),
    subscriptions: [
      {
        ...base("subscription-industrial-demo"),
        organizationId: ORGANIZATION_ID,
        planId: "plan-operation",
        status: "active",
        billingCycle: "monthly",
        currentPeriodStart: iso(-10_000),
        currentPeriodEnd: iso(33_200),
        provider: "manual",
      },
    ],
    organizations: [
      {
        ...base(ORGANIZATION_ID),
        name: "Comedor Industrial Demo",
        slug: "comedor-industrial-demo",
        businessProfileId: "profile-industrial-canteen",
        planId: "plan-operation",
        countryCode: "MX",
        timezone: "America/Chihuahua",
        currency: "MXN",
        estimatedEmployees: 850,
        plannedBranches: 2,
        onboardingStatus: "ready",
        activeModules: [...INDUSTRIAL_MODULES],
        status: "active",
      },
    ],
    branches: [
      {
        ...base(NORTH_BRANCH_ID),
        organizationId: ORGANIZATION_ID,
        name: "Planta Norte",
        code: "NORTE",
        timezone: "America/Chihuahua",
        address: "Complejo industrial norte",
        status: "active",
      },
      {
        ...base(SOUTH_BRANCH_ID),
        organizationId: ORGANIZATION_ID,
        name: "Planta Sur",
        code: "SUR",
        timezone: "America/Chihuahua",
        address: "Complejo industrial sur",
        status: "active",
      },
    ],
    roles: [
      {
        ...base("role-owner"),
        organizationId: ORGANIZATION_ID,
        name: "Dueño",
        permissions: ALL_PERMISSIONS,
        status: "active",
      },
      {
        ...base("role-supervisor"),
        organizationId: ORGANIZATION_ID,
        name: "Supervisor",
        permissions: [
          "dashboard.read",
          "employees.read",
          "attendance.read",
          "attendance.adjust",
          "services.read",
          "services.override",
          "inventory.read",
          "quality.read",
          "quality.write",
          "audit.read",
        ],
        status: "active",
      },
      {
        ...base("role-operator"),
        organizationId: ORGANIZATION_ID,
        name: "Operador",
        permissions: ["attendance.read", "services.read", "quality.read", "quality.write"],
        status: "active",
      },
    ],
    users: [
      {
        ...base(SYSTEM_USER_ID),
        organizationId: ORGANIZATION_ID,
        name: "Dirección Demo",
        email: "direccion@demo.kitchenmind.mx",
        roleId: "role-owner",
        branchIds: [NORTH_BRANCH_ID, SOUTH_BRANCH_ID],
        platformAccess: "owner",
        status: "active",
      },
      {
        ...base("user-supervisor-demo"),
        organizationId: ORGANIZATION_ID,
        name: "Supervisión Demo",
        email: "supervision@demo.kitchenmind.mx",
        roleId: "role-supervisor",
        branchIds: [NORTH_BRANCH_ID],
        status: "active",
      },
    ],
    shifts: [
      {
        ...base("shift-1"),
        organizationId: ORGANIZATION_ID,
        name: "Turno 1",
        startTime: "06:00",
        endTime: "14:00",
        toleranceMinutes: 10,
        status: "active",
      },
      {
        ...base("shift-2"),
        organizationId: ORGANIZATION_ID,
        name: "Turno 2",
        startTime: "14:00",
        endTime: "22:00",
        toleranceMinutes: 10,
        status: "active",
      },
      {
        ...base("shift-3"),
        organizationId: ORGANIZATION_ID,
        name: "Turno 3",
        startTime: "22:00",
        endTime: "06:00",
        toleranceMinutes: 10,
        status: "active",
      },
    ],
    clients: [
      { ...base("client-alpha"), organizationId: ORGANIZATION_ID, name: "Operaciones Alpha", code: "ALPHA", status: "active" },
      { ...base("client-beta"), organizationId: ORGANIZATION_ID, name: "Manufactura Beta", code: "BETA", status: "active" },
    ],
    employees: [
      {
        ...base("employee-001"),
        organizationId: ORGANIZATION_ID,
        branchId: NORTH_BRANCH_ID,
        employeeNumber: "N-001",
        name: "Mariana Torres",
        status: "active",
        shiftId: "shift-1",
        clientId: "client-alpha",
        employeeIdentifier: { type: "qr", value: "KM-N-001", active: true, assignedAt: iso(-9_000) },
      },
      {
        ...base("employee-002"),
        organizationId: ORGANIZATION_ID,
        branchId: NORTH_BRANCH_ID,
        employeeNumber: "N-002",
        name: "Daniel Ríos",
        status: "active",
        shiftId: "shift-1",
        clientId: "client-alpha",
        employeeIdentifier: { type: "barcode", value: "750000000002", active: true, assignedAt: iso(-8_900) },
      },
      {
        ...base("employee-003"),
        organizationId: ORGANIZATION_ID,
        branchId: NORTH_BRANCH_ID,
        employeeNumber: "N-003",
        name: "Paola Mendoza",
        status: "active",
        shiftId: "shift-2",
        clientId: "client-beta",
        employeeIdentifier: { type: "qr", value: "KM-N-003", active: true, assignedAt: iso(-8_800) },
      },
      {
        ...base("employee-004"),
        organizationId: ORGANIZATION_ID,
        branchId: SOUTH_BRANCH_ID,
        employeeNumber: "S-004",
        name: "Sergio Acosta",
        status: "active",
        shiftId: "shift-1",
        clientId: "client-beta",
        employeeIdentifier: { type: "manual", value: "KM-S-004", active: true, assignedAt: iso(-8_700) },
      },
      {
        ...base("employee-005"),
        organizationId: ORGANIZATION_ID,
        branchId: SOUTH_BRANCH_ID,
        employeeNumber: "S-005",
        name: "Lucía Navarro",
        status: "active",
        shiftId: "shift-3",
        clientId: "client-alpha",
        employeeIdentifier: { type: "qr", value: "KM-S-005", active: true, assignedAt: iso(-8_600) },
      },
      {
        ...base("employee-006"),
        organizationId: ORGANIZATION_ID,
        branchId: NORTH_BRANCH_ID,
        employeeNumber: "N-006",
        name: "Iván Castillo",
        status: "inactive",
        shiftId: "shift-2",
        clientId: "client-beta",
      },
    ],
    attendanceEvents: [
      {
        ...base("attendance-demo-1", -160),
        organizationId: ORGANIZATION_ID,
        branchId: NORTH_BRANCH_ID,
        employeeId: "employee-001",
        timestamp: iso(-155),
        eventType: "entry",
        deviceId: "kiosk-north-01",
        idempotencyKey: `attendance:employee-001:${iso(-155).slice(0, 16)}`,
        source: "scanner",
        syncStatus: "synced",
      },
      {
        ...base("attendance-demo-2", -140),
        organizationId: ORGANIZATION_ID,
        branchId: NORTH_BRANCH_ID,
        employeeId: "employee-002",
        timestamp: iso(-138),
        eventType: "late",
        deviceId: "kiosk-north-01",
        idempotencyKey: `attendance:employee-002:${iso(-138).slice(0, 16)}`,
        source: "scanner",
        syncStatus: "synced",
      },
      {
        ...base("attendance-demo-3", -120),
        organizationId: ORGANIZATION_ID,
        branchId: SOUTH_BRANCH_ID,
        employeeId: "employee-004",
        timestamp: iso(-118),
        eventType: "entry",
        deviceId: "kiosk-south-01",
        idempotencyKey: `attendance:employee-004:${iso(-118).slice(0, 16)}`,
        source: "scanner",
        syncStatus: "synced",
      },
    ],
    serviceTypes: [
      { ...base("service-breakfast"), organizationId: ORGANIZATION_ID, name: "Desayuno", startTime: "05:00", endTime: "10:59", status: "active" },
      { ...base("service-lunch"), organizationId: ORGANIZATION_ID, name: "Comida", startTime: "11:00", endTime: "17:59", status: "active" },
      { ...base("service-dinner"), organizationId: ORGANIZATION_ID, name: "Cena", startTime: "18:00", endTime: "23:59", status: "active" },
      { ...base("service-snack"), organizationId: ORGANIZATION_ID, name: "Colación", startTime: "00:00", endTime: "04:59", status: "active" },
    ],
    serviceEvents: [
      {
        ...base("service-demo-1", -90),
        organizationId: ORGANIZATION_ID,
        branchId: NORTH_BRANCH_ID,
        employeeId: "employee-001",
        clientId: "client-alpha",
        serviceTypeId: "service-lunch",
        timestamp: iso(-88),
        deviceId: "kiosk-services-north-01",
        idempotencyKey: `service:employee-001:service-lunch:${new Date().toISOString().slice(0, 10)}`,
        source: "scanner",
        syncStatus: "synced",
        override: false,
      },
      {
        ...base("service-demo-2", -70),
        organizationId: ORGANIZATION_ID,
        branchId: SOUTH_BRANCH_ID,
        employeeId: "employee-004",
        clientId: "client-beta",
        serviceTypeId: "service-lunch",
        timestamp: iso(-68),
        deviceId: "kiosk-services-south-01",
        idempotencyKey: `service:employee-004:service-lunch:${new Date().toISOString().slice(0, 10)}`,
        source: "scanner",
        syncStatus: "synced",
        override: false,
      },
    ],
    products: [
      { ...base("product-rice"), organizationId: ORGANIZATION_ID, name: "Arroz", sku: "ALI-001", baseUnit: "kg", category: "Abarrotes", minimumStock: 20, status: "active" },
      { ...base("product-chicken"), organizationId: ORGANIZATION_ID, name: "Pechuga de pollo", sku: "PRO-002", baseUnit: "kg", category: "Proteínas", minimumStock: 18, status: "active" },
      { ...base("product-tortilla"), organizationId: ORGANIZATION_ID, name: "Tortilla", sku: "ALI-003", baseUnit: "kg", category: "Abarrotes", minimumStock: 15, status: "active" },
      { ...base("product-oil"), organizationId: ORGANIZATION_ID, name: "Aceite vegetal", sku: "ALI-004", baseUnit: "l", category: "Abarrotes", minimumStock: 10, status: "active" },
    ],
    inventoryLots: [
      { ...base("lot-rice-1"), organizationId: ORGANIZATION_ID, branchId: NORTH_BRANCH_ID, productId: "product-rice", supplierId: "supplier-central", receivedAt: iso(-12_000), expiresAt: iso(80_000), quantity: 38, unit: "kg", location: "Almacén A", unitCost: 31 },
      { ...base("lot-chicken-1"), organizationId: ORGANIZATION_ID, branchId: NORTH_BRANCH_ID, productId: "product-chicken", supplierId: "supplier-protein", receivedAt: iso(-4_000), expiresAt: iso(3_000), quantity: 11, unit: "kg", location: "Cuarto frío", unitCost: 92 },
      { ...base("lot-tortilla-1"), organizationId: ORGANIZATION_ID, branchId: SOUTH_BRANCH_ID, productId: "product-tortilla", supplierId: "supplier-central", receivedAt: iso(-2_000), expiresAt: iso(1_400), quantity: 22, unit: "kg", location: "Almacén A", unitCost: 24 },
      { ...base("lot-oil-1"), organizationId: ORGANIZATION_ID, branchId: SOUTH_BRANCH_ID, productId: "product-oil", supplierId: "supplier-central", receivedAt: iso(-8_000), quantity: 8, unit: "l", location: "Almacén B", unitCost: 39 },
    ],
    inventoryMovements: [
      { ...base("movement-waste-1", -320), organizationId: ORGANIZATION_ID, branchId: NORTH_BRANCH_ID, productId: "product-chicken", lotId: "lot-chicken-1", movementType: "waste", quantity: 2, unit: "kg", reason: "Empaque dañado en recepción", estimatedCost: 184 },
    ],
    suppliers: [
      { ...base("supplier-central"), organizationId: ORGANIZATION_ID, name: "Distribuidora Central Demo", contactName: "Atención comercial", phone: "614 000 0101", status: "active" },
      { ...base("supplier-protein"), organizationId: ORGANIZATION_ID, name: "Proteínas del Norte Demo", contactName: "Ventas", phone: "614 000 0102", status: "active" },
    ],
    purchaseOrders: [
      {
        ...base("purchase-demo-1", -500),
        organizationId: ORGANIZATION_ID,
        branchId: NORTH_BRANCH_ID,
        supplierId: "supplier-protein",
        status: "suggested",
        expectedAt: iso(1_440),
        lines: [{ productId: "product-chicken", quantity: 18, unit: "kg", unitCost: 94, reason: "Stock por debajo del mínimo y consumo previsto." }],
      },
    ],
    qualityTemplates: [
      {
        ...base("quality-cold-room"),
        organizationId: ORGANIZATION_ID,
        name: "Temperatura de cuarto frío",
        category: "temperature",
        frequency: "Dos veces por turno",
        area: "Cuarto frío",
        fields: [{ id: "field-temperature", label: "Temperatura", type: "number", unit: "°C", minimum: 0, maximum: 4, required: true }],
        status: "active",
      },
      {
        ...base("quality-chlorine"),
        organizationId: ORGANIZATION_ID,
        name: "Concentración de cloro",
        category: "chlorine",
        frequency: "Antes de cada proceso",
        area: "Procesos",
        fields: [{ id: "field-chlorine", label: "Concentración", type: "number", unit: "ppm", minimum: 90, maximum: 110, required: true }],
        status: "active",
      },
    ],
    qualitySubmissions: [],
    correctiveActions: [],
    auditEvents: [
      {
        ...base("audit-demo-1", -500),
        organizationId: ORGANIZATION_ID,
        branchId: NORTH_BRANCH_ID,
        actorId: SYSTEM_USER_ID,
        action: "purchase.suggested",
        entity: "purchaseOrder",
        entityId: "purchase-demo-1",
        after: { status: "suggested", reason: "Stock bajo" },
        reason: "Sugerencia automática basada en mínimo configurado.",
        timestamp: iso(-500),
      },
    ],
  };
}
